language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t parmanbabra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parmanbabra/docker-react npm run test --coverage